server:
    port: ${PORT:8080}

spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}

    flyway:
        enabled: true
        baseline-on-migrate: true
        locations: classpath:db/migration

jwt:
    secret: ${JWT_SECRET}
    expiration: 48h

usage:
    bonus-amount: 3

apple:
    signin:
        audience: ${EXPO_PUBLIC_IOS_BUNDLE_ID}
    store:
        private-key-path: ${APPLE_STORE_PRIVATE_KEY}
        key-id: ${APPLE_KEY_ID}
        issuer-id: ${APPLE_ISSURE_ID}
        bundle-id: ${APPLE_BUNDLE_ID}
        environment: ${APPLE_STORE_ENVIRONMENT:SANDBOX}
        subscription-product-id: ${APPLE_SUBSCRIPTION_PRODUCT_ID}
        app-apple-id: ${APPLE_APP_APPLE_ID:}
        root-certificate-paths: ${APPLE_ROOT_CERTIFICATE_PATHS:}

openai:
    api-key: ${OPENAI_API_KEY}
